# -*- coding: utf-8 -*-
"""Blending and pasting .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-oCUgd5AedeA7fsKUaTBfuAOlzDAl2xT
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
print('Imported')

large_img = cv2.imread('/content/images.jpg')
watermark = cv2.imread('/content/good-vibes-positive-thoughts-letterings-260nw-1710352831.jpg')
cv2_imshow(large_img)
cv2_imshow(watermark)

print (large_img.shape)
print (watermark.shape)

img1 = cv2.resize(large_img,(800,600))
img2 = cv2.resize(watermark,(800,600))
cv2_imshow(img1)
cv2_imshow(img2)

blended = cv2.addWeighted(img1, 0.5, img2, 0.5, 0)
cv2_imshow(blended)

large_img = cv2.imread('/content/images.jpg')
watermark = cv2.imread('/content/good-vibes-positive-thoughts-letterings-260nw-1710352831.jpg')
cv2_imshow(large_img)
cv2_imshow(watermark)

high=watermark
small=large_img

x_offset=0
y_offset=0

x_end=x_offset+small.shape[1]
y_end=y_offset+small.shape[0]

small.shape

high[y_offset:y_end,x_offset:x_end]=small
plt.imshow(high)