# -*- coding: utf-8 -*-
"""edge detection .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zO54RSI_4hGrD618RSvo8qW7NubOoJ0q
"""

import cv2 
import numpy as np 
import matplotlib.pyplot as plt
from PIL import Image
from google.colab.patches import cv2_imshow

img=cv2.imread('/content/phones-switch-apps.jpg')
plt.imshow(img)

edges=cv2.Canny(image=img,threshold1=127,threshold2=127)
plt.imshow(edges)

edges=cv2.Canny(image=img,threshold1=0,threshold2=20)
plt.imshow(edges)

med_val=np.median(img)
med_val

lower=int(max(0,0.7*med_val))
upper=int(min(255,1.3*med_val))

edges=cv2.Canny(image=img,threshold1=lower,threshold2=upper+100)
plt.imshow(edges)

upper

blurred_img=cv2.blur(img,ksize=(7,7))

edges=cv2.Canny(image=blurred_img,threshold1=lower,threshold2=upper+50)
plt.imshow(edges)