# -*- coding: utf-8 -*-
"""Grid detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JkOSDPaVHwraFKolZjPLtOIfcX3jcAA5
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
from google.colab.patches import cv2_imshow
print('Imported')

flat_chess=cv2.imread('/content/chessboard.jpg')
plt.imshow(flat_chess)

found,corners=cv2.findChessboardCorners(flat_chess,(7,7))
found

cv2.drawChessboardCorners(flat_chess,(7,7),corners,found)

plt.imshow(flat_chess)

dots=cv2.imread('/content/tile-pattern-black-polka-dots-on-white-background-vector-2893888.jpg')
plt.imshow(dots)

found,corners=cv2.findCirclesGrid(dots,(10,10),cv2.CALIB_CB_SYMMETRIC_GRID)
found

cv2.drawChessboardCorners(dots,(10,10),corners,found)

plt.imshow(dots)