# -*- coding: utf-8 -*-
"""mouseclick.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OLUcFUCZTszCzTuwIaln9YfeSymrk6xN
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
from google.colab.patches import cv2_imshow
print('Imported')

drawing = False
ix,iy=-1,-1

def draw_rectangle(event,x,y,flages,params):
  global ix,iy,drawing
  if event == cv2.EVENT_LBUTTONDOWN:
      drawing = True
      ix,iy = x,y
  elif event == cv2.EVENT_MOUSEMOVE:
      if drawing == True:
          cv2.rectangle(img,(ix,iy),(x,y),(0,255,0),-1)
  elif event == cv2.EVENT_LBUTTONUP:
      drawing = False
      cv2.rectangle(img,(ix,iy),(x,y),(0,255,0),-1)

img=np.zeros((512,512,3))
cv2.namedWindow(winname='my_drawing')
cv2.setMouseCallback('my_drawing',draw_rectangle)

